#!/bin/bash
#
# shellcheck disable=SC1091
#

readonly TPDIFF_TEST_DIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)

. "$TPDIFF_TEST_DIR/lib.sh"

TPDIFF_COMMAND="${TPDIFF_TEST_DIR}/../tpdiff"
TPDIFF_TEST_RUN_SHELL="${TEST_SH:-bash}"

echo "test shell => $TPDIFF_TEST_RUN_SHELL"
echo

tpdiff_assert_colorize_to_change 'ingress.#: "1" => "2"'
tpdiff_assert_colorize_to_insert 'ingress.#:  "" => "1"'
tpdiff_assert_colorize_to_delete 'ingress.#: "1" => ""'

tpdiff_assert_not_colorize '+ aws_security_group.app'
tpdiff_assert_not_colorize 'ingress.#: "1" => "1"'
tpdiff_assert_not_colorize 'ingress.#:  "" => ""'
tpdiff_assert_not_colorize 'Apply complete!'

tpdiff_summary
tpdiff_status
