#!/bin/bash
#
# shellcheck disable=SC1091
#

readonly TPDIFF_TEST_DIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)

. "$TPDIFF_TEST_DIR/lib.sh"

TPDIFF_COMMAND="${TPDIFF_TEST_DIR}/../tpdiff"
TPDIFF_TEST_RUN_SHELL="${TEST_SH:-bash}"

echo "test shell => $TPDIFF_TEST_RUN_SHELL"
echo

tpdiff_assert_colorize 'ingress.#: "1" => "2"' 'changed'
tpdiff_assert_colorize 'ingress.#:  "" => "1"' 'added'
tpdiff_assert_colorize 'ingress.#: "1" => ""'  'removed'

tpdiff_assert_not_colorize '+ aws_security_group.app' 'resource description'
tpdiff_assert_not_colorize 'ingress.#: "1" => "1"'    'no change'
tpdiff_assert_not_colorize 'ingress.#:  "" => ""'     'no change (empty)'
tpdiff_assert_not_colorize 'Apply complete!'          'result line'

tpdiff_summary
tpdiff_status
