#!/bin/sh

TPDIFF_ANSI_ESCAPE_CODE=${TPDIFF_ANSI_ESCAPE_CODE-$(printf '\033')}

TPDIFF_COLOR_CHANGE=${TPDIFF_COLOR_CHANGE-'[33m'} # yellow
TPDIFF_COLOR_INSERT=${TPDIFF_COLOR_INSERT-'[32m'} # green
TPDIFF_COLOR_DELETE=${TPDIFF_COLOR_DELETE-'[31m'} # red

__tpdiff_colorize_to() {
    (
        color="$1"
        escape="$TPDIFF_ANSI_ESCAPE_CODE"

        echo "${escape}${color}&${escape}[m"
    )
}

__tpdiff_colorize_change() {
    __tpdiff_colorize_to "$TPDIFF_COLOR_CHANGE"
}

__tpdiff_colorize_insert() {
    __tpdiff_colorize_to "$TPDIFF_COLOR_INSERT"
}

__tpdiff_colorize_delete() {
    __tpdiff_colorize_to "$TPDIFF_COLOR_DELETE"
}

if [ -p /dev/stdin ] ; then
    cat -
else
    if [ ! $# -ge 1 ] ; then
        echo "$0: [ERROR] You must specify file."
        exit 1;
    fi

    if [ ! -f "$1" ] ; then
        echo "$0: [ERROR] \"$1\" No such file."
        exit 1;
    fi

    cat "$1"
fi | sed -e '
       /".*" => ".*"$/!b
       /^.*: *"" => ".\{1,\}"$/  s/.*/'"$(__tpdiff_colorize_insert)"'/
       t
       /^.*: *".\{1,\}" => ""$/  s/.*/'"$(__tpdiff_colorize_delete)"'/
       t
       /^.*: *"\(.*\)" => "\1"$/!s/.*/'"$(__tpdiff_colorize_change)"'/
     '
